version: '3.8'

services:
  spring-boot-app:
    image: "${DOCKER_HUB_IMAGE:-your-default-image}" # Image name passed as argument or fallback to default
    ports:
      - "8089:8089"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
